version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://bookuser:bookpass@db:5432/bookmanagement
      - SECRET_KEY=your-super-secret-key-change-in-production
      - DEBUG=True
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=bookmanagement
      - POSTGRES_USER=bookuser
      - POSTGRES_PASSWORD=bookpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: